export const PUZZLES = [
    {
        title: 'Tutorial',
        answer: '1054',
        location: 'In front of the house',
        puzzleText: "What are the first 4 digits of our home address?",
        hintOne: 'Look at the address of our home besides the door, the first four digits are the answer.',
        hintTwo: "A home is a thing people live inside, youre looking at one right now. Numbers are squiggles that represent how many of a thing.",
        urlText: "tutorial"
    },
    {
        title: 'Binoculars and a Compass',
        answer: '4848',
        location: 'Back porch',
        puzzleText: 'Take a look. 186 degrees SSW, or the 31st minute on a clock. 400 meters.',
        hintOne: "The degrees are in reference to a compass heading. The house behind you is due North.",
        hintTwo: "hint two",
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "binoculars"

    },
    {
        title: 'Bar of Soap',
        answer: '1234',
        location: 'Kitchen',
        puzzleText: "We're planning for a breakout at midnight, but the guards got ears everywhere. We've got a guy in the supply wing whose gonna send us a code for the lock on the doors, but he's gonna have to sneak it somewhere only the workers can see. The guards are on high alert, so make sure to keep your hands CLEAN. Be on the lookout",
        hintOne: "hint1",
        hintTwo: "hint2",
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "soap"
    },
    {
        title: 'Photo Spot the Difference',
        answer: '1234',
        location: 'Place',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "difference"
    },
    {
        title: 'Dollhouse',
        answer: 1234,
        location: 'Living Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "dollhouse"
    },
    {
        title: 'Forbidden Snacks',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "forbiddenSnacks"
    },
    {
        title: 'Give us a Dollar!',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "dollar"
    },
    {
        title: 'Group A and B Share Info',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "groupAB"
    },
    {
        title: 'Gift of Garf',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "garf"
    },
    {
        title: 'Magic Eye',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "magicEye"
    },
    {
        title: "Hey kids, what's for dinner?",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "menu"
    },
    {
        title: "Map between the fams",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "map"
    },
    {
        title: "Reconnecting with Family",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "reconnecting"
    },
    {
        title: "Bird call",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "birdCall"
    },
    {
        title: "Food Calulation",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "foodCalulation"
    },
    {
        title: "Cat Clocks",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "fatherTime"
    },
    {
        title: "Wedding Slideshow",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "slideshow"
    },
    {
        title: "letterboxd",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "letterboxd"
    },
    {
        title: "Hues and Clues",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "huesAndClues"
    },
    {
        title: "Mario Maker",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "marioMaker"    
    },
    {
        title: "J's microscope",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "jMicroscope"
    },
    {
        title: "Piano Keys",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "pianoKeys"
    },
    {
        title: "multistage word search",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: 'wordSearch'
    },
    {
        title: "origami fortune teller",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "fortuneTeller"
    },
    {
        title: "Book page search",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "bookPageSearch",
    },
    {
        title: "Pickpocket party hosts",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "pickpocket"
    },
    {
        title: "talking backwards",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "talkingBackwards"
    },
    {
        title: "how to sheet fakeout",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "fakeout"
    }, 
    {
        title: 'fat cats',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "fatCats"
    },
    {
        title: 'Mike vows',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "mikeVows"
    },
    {
        title: 'Brenna vows',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "brennaVows"
    },
    {
        title: 'Bedroom ceiling cutout',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "ceilingCutout"
    },
    {
        title: 'caffeine content',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "caffeineContent"
    },
    {
        title: 'Wedding wish tree',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "weddingWishTree"
    },
    {
        title: 'Plants need Sunlight',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "plantsNeedSun"
    },
    {
        title: 'invisible ink',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "invisibleInk"
    },
    {
        title: 'Laurence',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "laurence"    
    },
    {
        title: 'Brens sci-fi pulp books',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "pulpBooks"
    },
    {
        title: 'the final puzzle',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "finalPuzzle"
    }


]