export const PUZZLES = [
    {
        title: 'The Beginning Begins',
        answer: '1054',
        location: 'In front of the house',
        puzzleText: "What are the first 4 digits of our home address?",
        hintOne: 'Look at the address of our home beside the door, the first four digits are the answer.',
        hintTwo: "A home is a thing people live inside, youre looking at one right now. Numbers are squiggles that represent how many of a thing.",
        urlText: "theBeginningBegins"
    },
    {
        title: 'The Golden Compass',
        answer: '4848',
        location: 'Back porch',
        puzzleText: 'Take a look. 186 degrees SSW, or the 31st minute on a clock. 400 meters.',
        hintOne: "The degrees are in reference to a compass heading. The house behind you is due North.",
        hintTwo: "You are supposed to stand in the taped off circle on the back deck and pick up the compass, point it at the heading then look through the binoculars to see a painted sign in the distance that has the answer to the riddle written on it.",
        resetText: "Please put the binoculars down on the table on top of the instructions for focusing them, and the compass next to it.",
        urlText: "theGoldenCompass"

    },
    {
        title: 'Behind Bars',
        answer: '7114',
        location: 'Kitchen',
        puzzleText: "We're planning for a breakout at midnight, but the guards got ears everywhere. We've got a guy in the supply wing whose gonna send us a code for the lock on the doors, but he's gonna have to sneak it somewhere only the workers can see. The guards are on high alert, so make sure to keep your hands CLEAN. Be on the lookout",
        hintOne: "Our guy in the supply room mentioned something about a bar.",
        hintTwo: "You gotta look at the bar of soap.",
        resetText: "Here's how to reset",
        urlText: "behindBars"
    },
    {
        title: "You've Really Changed...",
        answer: '1234',
        location: 'Place',
        puzzleText: 'I think I saw this photo before elsewhere. Notice anything different? I see four. [This answer will have all of its digits going from lowest to highest, left to right]',
        hintOne: 'One of you is currently holding the other photo this moment.',
        hintTwo: 'Compare the photo on the wall with the photo on the front of your answer sheet. Whichever numbered squares contain something changed or different, that number goes into your final answer of 4 digits.',
        resetText: "If you took the photo down to look closer, please make sure you hang it back up after the fact.",
        urlText: "youveReallyChanged"
    },
    {
        title: 'A Small Dilemma',
        answer: 1234,
        location: 'Living Room',
        puzzleText: 'Miniature Mike was getting all of the player packets ready for the guests at his Miniature Marriage, when a gust of wind came by and blew them all over the front of his house. Even worse, one of the sheets already had the answer to THIS PUZZLE written in. I guess if you can find the right sheet, the answer is yours for the taking.',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Place the magnifying glass back next to the table, and if any furniture got moved or knocked over during your inspection, please make sure to put it back as best you can or get one of the game hosts to help reset it.",
        urlText: "aSmallDilemma"
    },
    {
        title: 'Forbidden Snacks',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: "Your puzzle isn't here. You'll have to keep looking around the house. Keep an eye out for a forbidden dish, not to be enjoyed until after 10 PM, then ignore its warning and look inside.",
        hintOne: 'There should be snacks somewhere on the main floor.',
        hintTwo: 'There is a metal tray on the snack table in the dining room next to the kitchen. It says "Do Not Enjoy", but you can go for it',
        resetText: "Please make sure to pull the foil back across the top of the tray so the insides remain covered to anyone else. Make sure the note on top is propped up and visible.",
        supplementaryItems: "Here's some supplementary items",
        urlText: "forbiddenSnacks"
    },
    {
        title: 'Give us a Dollar!',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: "Give us a dollar. Please. We want to go to Japan. Don't we deserve it? Go to our Registry and give us a dollar. You don't have to send the dollar now, you can even send it on Venmo later tonight when you leave the party and think 'That was a good party, we should really hang out with Mike and Brenna more often. I can't wait to get home to watch the new episode of House of the Dragon. It's not as good as Game of Thrones neccessarily, but I think it has the chance to get there at some point.' Either way, go to the registry and scroll through until you see the answer to this puzzle. (You don't really have to give us a dollar, but do click through to the site for the code!)",
        hintOne: 'Click the link to the registry and scroll down to the option titled "code"',
        hintTwo: "If you can't connect to the site for some reason, the answer is [ANSWER]",
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "giveUsADollar"
    },
    {
        title: 'Group A and B Share Info',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "groupAB"
    },
    {
        title: 'Gift of Garf',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'Place your Garfield at the shrine, in exchange, pickup the paper Garfield head and gently pull on his tongue to reveal the answer. If you forgot to bring something Garfield related, please take the markers next to you and draw Garfield in under 60 seconds, sign your name to the bottom or back, then put it in the offering box before revealing the code. This is the honor system bb.',
        hintOne: "If you forgot to bring something Garfield related, just do a quick doodle of Garfield. Don't worry about judgement, we REALLY want some bad Garfield drawings.",
        hintTwo: "Garfield is some kind of voluptuous sassy orange cat with an 'I don't give a fuck' attitude and an insatiable hunger for noodles in gravy. He has whiskers coming off the sides of his head, two big hard boiled eggs for eyes, and wavy black stripes on his back. You gotta know who Garfield is bud.",
        resetText: "Please make sure the Garfield mouth closes and is placed back down on the table face up for others to reveal for themselves.",
        urlText: "giftOfGarf"
    },
    {
        title: "I think it's ... a sailboat?",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'Stare at the poster, relax your eyes and try and look past it, until the code reveals itself to you. There is only 1 number, so just repeat it 4 times for the answer.',
        hintOne: "These can be hard or impossible for some people to do, just try for a minute or two and if you still can't, try getting up close to it.",
        hintTwo: "Look REALLY close to it, like, go look at the frame of the poster. It's alright you couldn't see it in the poster. Don't sweat it though, not everyone's eyes can do it. Good try I bet you looked really cool doing it.",
        resetText: "Relax your eyes and move along baby",
        supplementaryItems: "Here's some supplementary items",
        urlText: "magicEye"
    },
    {
        title: "Hey kids, what's for dinner?",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "menu"
    },
    {
        title: "Reconnecting with Family",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "reconnecting"
    },
    {
        title: "La Cage aux Folles",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'Did someone let a bird into our pristine home!? We need to identify it before calling the bird police or whatever. Download this app [HERE] for identifying bird calls, take note of the species, then find its entry in the book on the shelf next to you "Neighborhood Birding 101". The answer to this question will be the two page numbers its on. (For example, if a bird was on pages 10 and 11, the answer would be "1011")',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "birdCall"
    },
    {
        title: "Cat Clocks",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "fatherTime"
    },
    {
        title: "Wedding Slideshow",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "slideshow"
    },
    {
        title: "letterboxd",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "letterboxd"
    },
    {
        title: "Hues and Clues",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "huesAndClues"
    },
    {
        title: "Mario Maker",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "marioMaker"    
    },
    {
        title: "J's microscope",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "jMicroscope"
    },
    {
        title: "Piano Keys",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "pianoKeys"
    },
    {
        title: "multistage word search",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: 'wordSearch'
    },
    {
        title: "origami fortune teller",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "fortuneTeller"
    },
    {
        title: "Book page search",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "bookPageSearch",
    },
    {
        title: "Pickpocket party hosts",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "pickpocket"
    },
    {
        title: "talking backwards",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "talkingBackwards"
    },
    {
        title: "how to sheet fakeout",
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "fakeout"
    }, 
    {
        title: 'fat cats',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "fatCats"
    },
    {
        title: 'Mike vows',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "mikeVows"
    },
    {
        title: 'Brenna vows',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "brennaVows"
    },
    {
        title: 'Bedroom ceiling cutout',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "ceilingCutout"
    },
    {
        title: 'Plants need Sunlight',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "plantsNeedSun"
    },
    {
        title: 'invisible ink',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "invisibleInk"
    },
    {
        title: 'Laurence',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "laurence"    
    },
    {
        title: 'Brens sci-fi pulp books',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "pulpBooks"
    },
    {
        title: 'the final puzzle',
        answer: 1234,
        location: 'Dining Room',
        puzzleText: 'puzzleText',
        hintOne: 'hint1',
        hintTwo: 'hint2',
        resetText: "Here's how to reset",
        supplementaryItems: "Here's some supplementary items",
        urlText: "finalPuzzle"
    }


]